### ISSUE TITLE
uaa.yaml is not mapped

### ISSUE THREAD

**Issue by eskuai** [making/uaa-on-kubernetes#2]
Hi 

I am trying to deploy your k8s uaa, but i cant get to run because, the uaa.yml file is not mapping:

the uaa.file deployed into 
/usr/local/tomcat/webapps/ROOT/WEB-INF/classes/uaa.yml

is not the configured into configmaps definition...

tomcat is always running using a uaa.yml that it is not from configmap

any ideas?

**Comment by making** [comment]
This repo is not supposed to be used by someone.
I’m not maintaining it anymore
